import { RiWalkFill } from 'react-icons/ri';

export const images={
    BANNEROVERLAY: require('../assests/baner-overlay.png'),
    BANNER:require('../assests/banner.webp'),
    IDC: require('../assests/idc.webp'),
    GARTNER:require('../assests/gartner.webp'),
    FORRESTER:require('../assests/forrester.webp'),
    APPMANAGEMENT:require('../assests/app-management.webp'),
    AUTOMATION:require('../assests/automation.webp'),
    ENDPOINT: require('../assests/endpoint-security.webp'),
    INTEGRATIONS: require('../assests/integrations.webp'),
    REMOTE: require('../assests/remote-access.webp'),
    ZEROTOUCH: require('../assests/zero-touch.webp'),
    ANDROID: require('../assests/android.webp'),
    FIREOS: require('../assests/fireOS.webp'),
    IOS: require('../assests/iOS.webp'),
    MACOS: require('../assests/macOS.webp'),
    TVOS: require('../assests/tvOS.webp'),
    WINDOWS: require('../assests/windows.webp'),
    GORILLA: require('../assests/gorillas.webp'),
    POLARIS: require('../assests/polaris.webp'),
    MARRIOTT: require('../assests/marriott-intl.webp'),
    WOLT:require('../assests/wolt.webp'),
    MERCK: require('../assests/merck (1).webp'),
    COSTCO: require('../assests/costco.webp'),
    SAIC: require('../assests/saic.webp'),
    HILTON: require('../assests/hilton.webp'),
    LOWES: require('../assests/lowes.webp'),
    GROUP1: require('../assests/group1-automotive.webp'),
    CHRIS: require('../assests/chris-robinson.webp'),
    DALIBOR: require('../assests/dalibor-kruljac.webp'),
    LOGOWHITE: require('../assests/logo-white.png'),
    LOGOBLACK: require('../assests/logo-black.webp')
}